version: '2'
services:
  discord-soundbot:
    build: .
    image: soundbot
    volumes:
      - ./sounds:/app/sounds
      - ./config/config.json:/app/config/config.json
      - ./db.json:/app/db.json
